version: '2'
services:
  cartodb-postgresql:
    build: cartodb-postgresql/.
    ports:
      - "5432:5432"

  cartodb-redis:
    build: cartodb-redis/.
    ports:
      - "6379:6379"

  cartodb-sql-api:
    build: CartoDB-SQL-API/.
    ports:
      - "8125:8125"
    links:
      - cartodb-postgresql
      - cartodb-redis

  windshaft-cartodb:
    build: Windshaft-cartodb/.
    ports:
      - "6082:6082"
      - "6081:6081"
    environment:
      - CARTO_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CARTO_SESSION_DOMAIN=localdomain
      - CORS_ENABLED=true
      - WINDSHAFT_PORT=8181
