production:
  adapter: postgres
  encoding: unicode
  host: __DB_HOST__
  port: __DB_PORT__
  direct_port: __DB_PORT__
  database: carto_db_production
  username: __DB_USER__
  password:
  conn_validator_timeout: 900

staging:
  adapter: postgres
  encoding: unicode
  host: __DB_HOST__
  port: __DB_PORT__
  direct_port: __DB_PORT__
  database: carto_db_staging
  username: __DB_USER__
  password:
  conn_validator_timeout: 900

development:
  adapter: postgres
  encoding: unicode
  host: __DB_HOST__
  port: __DB_PORT__
  direct_port: __DB_PORT__
  database: carto_db_development
  username: __DB_USER__
  password:
  conn_validator_timeout: 900
  pool: 50

test:
  adapter: postgres
  encoding: unicode
  database: carto_db_test
  host: __DB_HOST__
  port: __DB_PORT__
  direct_port: __DB_PORT__
  username: __DB_USER__
  password:
  conn_validator_timeout: -1
